// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package database

import (
	"database/sql"
	"time"
)

type Org struct {
	ID          string
	Name        string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Description string
	CreatorID   string
}

type Project struct {
	ID          string
	Name        string
	Description string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	OrgID       string
}

type ProjectsTeam struct {
	ProjectID string
	TeamID    string
}

type RevokedToken struct {
	ID          string
	TokenString string
}

type Task struct {
	ID          string
	Name        string
	Description sql.NullString
	CreatedAt   time.Time
	UpdatedAt   time.Time
	ProjectID   string
}

type Team struct {
	ID        string
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
	OrgID     string
}

type TeamsUser struct {
	TeamID string
	UserID string
}

type User struct {
	ID        string
	Name      string
	Email     string
	Password  string
	CreatedAt time.Time
	UpdatedAt time.Time
}
