name: ci

on:
  pull_request:
    branches: [main]

jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"
      
      - name: Check out code
        uses: actions/checkout@v3

      - name: Run Go Unit Tests
        run: go test ./... -cover
        working-directory: ${{ github.workspace }}/backend

      - name: install gosec
        run: go install github.com/securego/gosec/v2/cmd/gosec@latest
        working-directory: ${{ github.workspace }}/backend

      - name: Run gosec Check
        run: gosec ./...
        working-directory: ${{ github.workspace }}/backend

  style:
    name: style
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Check out code
        uses: actions/checkout@v3

      - name: Run Go Format check
        run: test -z $(go fmt ./...)
        working-directory: ${{ github.workspace }}/backend

      - name: install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest
        working-directory: ${{ github.workspace }}/backend

      - name: Run staticcheck
        run: staticcheck ./...
        working-directory: ${{ github.workspace }}/backend